"""Create authentication tables

Revision ID: d5e828d1d173
Revises: 
Create Date: 2026-09-30 16:05:54.085165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e828d1d173'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_oauth_flows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('profile_token_hash', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_token_hash'),
    sa.UniqueConstraint('state_hash')
    )
    op.create_table('auth_rate_limits',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('auth_rate_limits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_rate_limits_expires_at'), ['expires_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('uq_users_verified_email', ['email'], unique=True, postgresql_where=sa.text('email_verified'), sqlite_where=sa.text('email_verified'))
        batch_op.create_index('uq_users_verified_phone', ['phone'], unique=True, postgresql_where=sa.text('phone_verified'), sqlite_where=sa.text('phone_verified'))

    op.create_table('auth_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('destination', sa.String(length=254), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('sends', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('sent_at', sa.BigInteger(), nullable=False),
    sa.Column('consumed_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_identities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject', name='uq_identity_subject')
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('access_hash', sa.String(length=64), nullable=False),
    sa.Column('access_expires_at', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('revoked_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_hash')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('auth_refresh_tokens',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('used_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['auth_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('auth_refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_refresh_tokens_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_refresh_tokens_session_id'))

    op.drop_table('auth_refresh_tokens')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))

    op.drop_table('auth_sessions')
    op.drop_table('auth_identities')
    op.drop_table('auth_challenges')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('uq_users_verified_phone', postgresql_where=sa.text('phone_verified'), sqlite_where=sa.text('phone_verified'))
        batch_op.drop_index('uq_users_verified_email', postgresql_where=sa.text('email_verified'), sqlite_where=sa.text('email_verified'))

    op.drop_table('users')
    with op.batch_alter_table('auth_rate_limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_rate_limits_expires_at'))

    op.drop_table('auth_rate_limits')
    op.drop_table('auth_oauth_flows')
    # ### end Alembic commands ###
